#!/bin/sh

set -e

ROOT=$(pwd)
BUILD="$ROOT/build"
version=$(cat VERSION)
rm -Rf ${BUILD}
mkdir -p ${BUILD}/release ${BUILD}/tmp

echo "Building version $version..."

ar="amd64 armhf"
for arch in ${ar}; do
    echo ${arch}

    rm -rf ${BUILD}/tmp/*
    mkdir -p ${BUILD}/tmp/usr/sbin
    cp -R deb/* ${BUILD}/tmp

    GOOS=linux GOARCH=$( echo ${arch} | sed 's/armhf/arm/g' ) go build -o ${BUILD}/hd-idle
    cd ${BUILD}
    tar zcf hd-idle-${version}.linux-${arch}.tar.gz hd-idle
    mv hd-idle-${version}.linux-${arch}.tar.gz ${BUILD}/release
    mv hd-idle ${BUILD}/tmp/usr/sbin/
    cd ${ROOT}

    gzip ${BUILD}/tmp/usr/share/man/man1/hd-idle.1

    size=$(du -cs ${BUILD}/tmp | sed '1!d' | grep -oe "^[0-9]*")
    sed -i 's/{{version}}/'${version}'/g;s/{{size}}/'${size}'/g;s/{{architecture}}/'${arch}'/g' ${BUILD}/tmp/DEBIAN/control

    chmod 0555 ${BUILD}/tmp/DEBIAN/p*
    fakeroot dpkg-deb -b -z9 ${BUILD}/tmp ${BUILD}/release
done

echo done